### ISSUE TITLE
Wireless

### ISSUE THREAD

**Issue by hjfabius** [hjfabius/domus-silicea#7]
The solution should consider the possibility to have the sensors connected to server wireless

**Comment by hjfabius** [comment]
Ciao,
    I started writing a wiki concerning network topology. I'll publish it in the coming days

**Comment by barthux** [comment]
Hi, will you use the standard github wiki? Let me know on which part I can start to work / investigate.

**Comment by hjfabius** [comment]
Yes, you can view it online or create a local repository using the following remote git [https://github.com/hjfabius/domus-silicea.wiki.git](https://github.com/hjfabius/domus-silicea.wiki.git)

**Comment by hjfabius** [comment]
If you have some spare time, I suggest you to start working on wiki related to:
- Project Scope 
- Requirement 

If you want to dig in some technical area, I read somewhere that arduino has a standard way to automatically identify shields when connected.  Try to find some document around it and understand if it can fit our idea.
